### ISSUE TITLE
frameGrab.nativeFrame returns incorrect width

### ISSUE THREAD

**Issue by vanniktech** [jcodec/jcodec#498]
I have the following snippet which reads a video file and extracts the width / height for a given frame:

```kotlin
val directory = File("sample-jvm/images/").takeIf { it.exists() } ?: File("images/")
val video = directory.resolve("video-1098x1952.mp4")

val channel = SeekableInMemoryByteChannel(video.inputStream().readBytes())
MP4Demuxer.createMP4Demuxer(channel).use { createMP4Demuxer ->
  val videoTrack = createMP4Demuxer.videoTrack as SeekableDemuxerTrack
  val frameGrab = FrameGrab(videoTrack, AVCMP4Adaptor(videoTrack.meta)).seekToSecondPrecise(0.0)
  val picture = frameGrab.nativeFrame
  println(picture.width) // Prints 1104 but should be 1098.
  println(picture.height) // Prints 1952 which is correct.
}
```

However jcodec tells me that the width is 1104, it is 1098 though. Ffmpeg also shows this: 

> Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1098x1952 [SAR 1:1 DAR 9:16], 2373 kb/s, 59 fps, 59 tbr, 15104 tbn (default)

[Public reproducer](https://github.com/vanniktech/blurhash/pull/45/files) - just open the project and run the BlurHashJvm file, which contains the same code as shown above.

**Comment by svitvitskiy** [comment]
I think this is because in h264 a frame is basically a collection of 16x16 macroblocks. So the picture that you get is just a raw decoded pixels that need to be clipped to the intended size that is stored in the header of the video.
In order to get the cropped version of the frame simply call '.cropped()' method on a Picture.
So would be something like:
`val picture = frameGrab.nativeFrame.cropped()`

**Comment by vanniktech** [comment]
I understand, this also works:

```diff
-picture.width
+picture.croppedWidth
```

Thanks for answering so quickly!
